-- CreateTable
CREATE TABLE `FastTrackScan` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `trayId` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `scannedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
